---
- name: Tomcat installation
  hosts: all
  become: yes
  tasks:
    - name: Installing Java 
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: Creating a System User
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        create_home: true 
        home: /opt/tomcat
        shell: /bin/false
