---
- name: Installtion of Tomcat on ubuntu machine
  hosts: appservers
  become: yes
  tasks: 
    - name: Installing Java
      ansible.builtin.package:
        name: "{{java_package_name}}"
        state: present