---
- name: Installtion of Tomcat on ubuntu machine
  hosts: appservers
  become: yes
  vars:
    java_package_name: openjdk-11-jdk
    user_name: tomcat
    group_name: tomcat
    user_home: /opt/tomcat
    user_shell: /bin/false
    tomcat_version: "10.1.9"
    tomcat_major_version: "10"
    tomcat_service_name: tomcat.service
  tasks: 
    - name: Installing Java
      ansible.builtin.package:
        name: "{{java_package_name}}"
        state: present