---
- name: install utility
  hosts: all
  tasks:
    - name: install utility
      ansible.builtin.package:
       name: "{{item}}"
       state: present
       loop: "{{packages}}"
    - name: debug variable
      ansible.builtin.debug:
        var: purpose     
    - name: the config file of ansible 
      ansible.builtin.debug:
        var: ansible_config_file    