---
- name: Installing Apache and Updating the Firewall
  hosts: all
  become: yes
  tasks: 
    - name: install Apache
      ansible.builtin.apt:
        name: apache2
        update_cache: true
        state: present
    - name: copy php
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php